import Form from "../Form/Form";

// var user = {
//   User_Id: "70590a02a99e1c061eac0318af82a7ae",
//   FirstName: "",
//   LastName: "Admin 269",
// };

// var documentData = {
//   N_Status: "1",
//   Res_Id: "271",
//   Filename: "5316066990105226476-submission",
//   Identifier: "PxEXkR0N4LeTR0iAb5yJeeWb8rzW4dNm",
//   Page_Count: "1",
//   Format: "pdf",
//   Creation_Date: "2022-06-21 09:46:16",
//   Modele_LAD: "4",
//   Id_Original: "271",
//   Commented: "0",
//   Upload_User_Id: "507d8a1b4a81037457ce6d17a2d2c9db",
//   Displayable_Creation_Date: "21/06/2022 09:46",
//   Original_Filesize: "196823",
//   FilesizeOriginal: "196823",
//   PDF_Filesize: "196823",
//   Filesize: "196823",
//   signed: "",
//   Statut_Signature: [],
//   Doublons: [],
//   Doublons_Inactifs: [],
//   signataires_oodrive: [],
//   signataires_oodrive_signed: [],
//   signataires_oodrive_waiting: [],
//   signataires_oodrive_refused: [],
//   Upload_User_Id_sort: "Agent DEPOT",
//   Coll_Id: "coll_11",
//   N_Client: 13941,
//   Shipment_Status: [],
//   Chorus_Status: [],
//   N_Modele_LAD: "4",
//   custom_t1: ["70590a02a99e1c061eac0318af82a7ae"],
//   custom_n3: [],
//   custom_d4: [],
//   custom_t5: ["test"],
//   custom_n4: [],
//   custom_n6: ["1"],
//   custom_d3: ["2022-06-21"],
//   custom_d5: [],
//   custom_f1: ["0.5"],
//   custom_n2: ["2"],
//   custom_t4: [],
//   custom_t3: ["70590a02a99e1c061eac0318af82a7ae"],
//   custom_n1: ["1"],
//   custom_d1: [],
//   custom_d2: [],
//   custom_t2: [],
//   folders: [],
//   custom_infos: {
//     custom_t1: {
//       Label: "Salari&eacute; | Nom Pr&eacute;nom",
//       Type: "USERS_LIST",
//     },
//     custom_t5: {
//       Label: "Cong&eacute;s | Motif",
//       Type: "TEXT",
//     },
//     custom_n6: {
//       Label: "Cong&eacute;s | Une 1/2 journ&eacute;e",
//       Type: "FOREIGN_TABLE",
//     },
//     custom_d3: {
//       Label: "Cong&eacute;s | Date de D&eacute;but",
//       Type: "DATE",
//     },
//     custom_f1: {
//       Label: "Cong&eacute;s | Total de jours",
//       Type: "FLOAT",
//     },
//     custom_n2: {
//       Label: "Cong&eacute;s | Type de cong&eacute;s",
//       Type: "FOREIGN_TABLE",
//     },
//     custom_t3: {
//       Label: "Validation | Valideur",
//       Type: "USERS_LIST",
//     },
//     custom_n1: {
//       Label: "Validation | Statut de validation",
//       Type: "FOREIGN_TABLE",
//     },
//   },
//   custom_t1_sort: ["Admin 269 "],
//   custom_t3_sort: ["Admin 269 "],
// };

// var tableauIndex = [
//   {
//     INDEX_ID: "161",
//     COLUMN: "custom_t1",
//     TYPE: "USERS_LIST",
//     LABEL: "Salari&eacute; | Nom Pr&eacute;nom",
//     SHORT_LABEL: " Nom Pr&eacute;nom",
//     COLL_ID: "coll_11",
//     AUTOCOMPLETE: false,
//     SHOW_IN_RESULTLIST: true,
//     MANDATORY: false,
//     MULTIVALUED: false,
//     EXCLU_LAD: false,
//     FIXED_VALUES_TABLE: false,
//     IS_EXTERNAL: true,
//     VALEURS: {
//       "70590a02a99e1c061eac0318af82a7ae": "Admin 269 ",
//       "28e3edb2369c1c89447a760f920914cc": "devspe ",
//     },
//     ORDER: false,
//     TABLENAME: "users",
//     FOREIGN_TABLE_ID: "61",
//     IS_PREDEFINED_LIST: false,
//     IS_DATE: false,
//     IS_INT: false,
//     IS_FLOAT: false,
//     IS_NUMERIC: false,
//     WIZARD: "",
//     SORTABLE: true,
//     STANDARDIZED_WIZARD: "",
//     Color_Id: "0",
//     Color_Code: "",
//   },
//   {
//     INDEX_ID: "151",
//     COLUMN: "custom_n3",
//     TYPE: "FOREIGN_TABLE",
//     LABEL: "Salari&eacute; | Service",
//     SHORT_LABEL: " Service",
//     COLL_ID: "coll_11",
//     AUTOCOMPLETE: false,
//     SHOW_IN_RESULTLIST: true,
//     MANDATORY: false,
//     MULTIVALUED: false,
//     EXCLU_LAD: false,
//     FIXED_VALUES_TABLE: false,
//     IS_EXTERNAL: true,
//     VALEURS: {
//       1: "ADMIN DEPT",
//       2: "SALES DEPT",
//       3: "SERVICE DEPT",
//       4: "TECHNICAL DEPT",
//     },
//     ORDER: true,
//     ORDER_WAY: "asc",
//     TABLENAME: "FT_11_2",
//     FOREIGN_TABLE_ID: "56",
//     IS_PREDEFINED_LIST: false,
//     IS_DATE: false,
//     IS_INT: true,
//     IS_FLOAT: false,
//     IS_NUMERIC: true,
//     WIZARD: "",
//     SORTABLE: true,
//     STANDARDIZED_WIZARD: "",
//     Color_Id: "0",
//     Color_Code: "",
//   },
//   {
//     INDEX_ID: "215",
//     COLUMN: "custom_d4",
//     TYPE: "DATE",
//     LABEL: "Cong&eacute;s | Date de la demande",
//     SHORT_LABEL: " Date de la demande",
//     COLL_ID: "coll_11",
//     AUTOCOMPLETE: false,
//     SHOW_IN_RESULTLIST: true,
//     MANDATORY: false,
//     MULTIVALUED: false,
//     EXCLU_LAD: false,
//     FIXED_VALUES_TABLE: false,
//     IS_EXTERNAL: false,
//     IS_PREDEFINED_LIST: false,
//     IS_DATE: true,
//     IS_INT: false,
//     IS_FLOAT: false,
//     IS_NUMERIC: false,
//     WIZARD: "",
//     SORTABLE: true,
//     STANDARDIZED_WIZARD: "",
//     Color_Id: "0",
//     Color_Code: "",
//   },
//   {
//     INDEX_ID: "235",
//     COLUMN: "custom_t5",
//     TYPE: "TEXT",
//     LABEL: "Cong&eacute;s | Motif",
//     SHORT_LABEL: " Motif",
//     COLL_ID: "coll_11",
//     AUTOCOMPLETE: false,
//     SHOW_IN_RESULTLIST: true,
//     MANDATORY: false,
//     MULTIVALUED: false,
//     EXCLU_LAD: false,
//     FIXED_VALUES_TABLE: false,
//     IS_EXTERNAL: false,
//     IS_PREDEFINED_LIST: false,
//     IS_DATE: false,
//     IS_INT: false,
//     IS_FLOAT: false,
//     IS_NUMERIC: false,
//     WIZARD: "",
//     SORTABLE: true,
//     STANDARDIZED_WIZARD: "",
//     Color_Id: "0",
//     Color_Code: "",
//   },
//   {
//     INDEX_ID: "190",
//     COLUMN: "custom_n4",
//     TYPE: "FOREIGN_TABLE",
//     LABEL: "Cong&eacute;s | Dur&eacute;e",
//     SHORT_LABEL: " Dur&eacute;e",
//     COLL_ID: "coll_11",
//     AUTOCOMPLETE: false,
//     SHOW_IN_RESULTLIST: true,
//     MANDATORY: false,
//     MULTIVALUED: false,
//     EXCLU_LAD: false,
//     FIXED_VALUES_TABLE: false,
//     IS_EXTERNAL: true,
//     VALEURS: {
//       1: "Une demie journée",
//       2: "Une journée",
//       3: "Plusieurs journées",
//     },
//     ORDER: true,
//     ORDER_WAY: "asc",
//     TABLENAME: "def_values_19",
//     FOREIGN_TABLE_ID: "73",
//     IS_PREDEFINED_LIST: false,
//     IS_DATE: false,
//     IS_INT: true,
//     IS_FLOAT: false,
//     IS_NUMERIC: true,
//     WIZARD: "",
//     SORTABLE: true,
//     STANDARDIZED_WIZARD: "",
//     Color_Id: "0",
//     Color_Code: "",
//   },
//   {
//     INDEX_ID: "154",
//     COLUMN: "custom_n6",
//     TYPE: "FOREIGN_TABLE",
//     LABEL: "Cong&eacute;s | Une 1/2 journ&eacute;e",
//     SHORT_LABEL: " Une 1/2 journ&eacute;e",
//     COLL_ID: "coll_11",
//     AUTOCOMPLETE: false,
//     SHOW_IN_RESULTLIST: true,
//     MANDATORY: false,
//     MULTIVALUED: false,
//     EXCLU_LAD: false,
//     FIXED_VALUES_TABLE: false,
//     IS_EXTERNAL: true,
//     VALEURS: {
//       1: "Oui",
//       2: "Non",
//     },
//     ORDER: true,
//     ORDER_WAY: "asc",
//     TABLENAME: "FT_11_4",
//     FOREIGN_TABLE_ID: "58",
//     IS_PREDEFINED_LIST: false,
//     IS_DATE: false,
//     IS_INT: true,
//     IS_FLOAT: false,
//     IS_NUMERIC: true,
//     WIZARD: "",
//     SORTABLE: true,
//     STANDARDIZED_WIZARD: "",
//     Color_Id: "0",
//     Color_Code: "",
//   },
//   {
//     INDEX_ID: "157",
//     COLUMN: "custom_d3",
//     TYPE: "DATE",
//     LABEL: "Cong&eacute;s | Date de D&eacute;but",
//     SHORT_LABEL: " Date de D&eacute;but",
//     COLL_ID: "coll_11",
//     AUTOCOMPLETE: false,
//     SHOW_IN_RESULTLIST: true,
//     MANDATORY: false,
//     MULTIVALUED: false,
//     EXCLU_LAD: false,
//     FIXED_VALUES_TABLE: false,
//     IS_EXTERNAL: false,
//     IS_PREDEFINED_LIST: false,
//     IS_DATE: true,
//     IS_INT: false,
//     IS_FLOAT: false,
//     IS_NUMERIC: false,
//     WIZARD: "",
//     SORTABLE: true,
//     STANDARDIZED_WIZARD: "",
//     Color_Id: "0",
//     Color_Code: "",
//   },
//   {
//     INDEX_ID: "158",
//     COLUMN: "custom_d5",
//     TYPE: "DATE",
//     LABEL: "Cong&eacute;s | Date de fin",
//     SHORT_LABEL: " Date de fin",
//     COLL_ID: "coll_11",
//     AUTOCOMPLETE: false,
//     SHOW_IN_RESULTLIST: true,
//     MANDATORY: false,
//     MULTIVALUED: false,
//     EXCLU_LAD: false,
//     FIXED_VALUES_TABLE: false,
//     IS_EXTERNAL: false,
//     IS_PREDEFINED_LIST: false,
//     IS_DATE: true,
//     IS_INT: false,
//     IS_FLOAT: false,
//     IS_NUMERIC: false,
//     WIZARD: "",
//     SORTABLE: true,
//     STANDARDIZED_WIZARD: "",
//     Color_Id: "0",
//     Color_Code: "",
//   },
//   {
//     INDEX_ID: "216",
//     COLUMN: "custom_f1",
//     TYPE: "FLOAT",
//     LABEL: "Cong&eacute;s | Total de jours",
//     SHORT_LABEL: " Total de jours",
//     COLL_ID: "coll_11",
//     AUTOCOMPLETE: false,
//     SHOW_IN_RESULTLIST: true,
//     MANDATORY: false,
//     MULTIVALUED: false,
//     EXCLU_LAD: false,
//     FIXED_VALUES_TABLE: false,
//     IS_EXTERNAL: false,
//     IS_PREDEFINED_LIST: false,
//     IS_DATE: false,
//     IS_INT: false,
//     IS_FLOAT: true,
//     IS_NUMERIC: true,
//     WIZARD: "",
//     SORTABLE: true,
//     STANDARDIZED_WIZARD: "",
//     Color_Id: "0",
//     Color_Code: "",
//   },
//   {
//     INDEX_ID: "160",
//     COLUMN: "custom_n2",
//     TYPE: "FOREIGN_TABLE",
//     LABEL: "Cong&eacute;s | Type de cong&eacute;s",
//     SHORT_LABEL: " Type de cong&eacute;s",
//     COLL_ID: "coll_11",
//     AUTOCOMPLETE: false,
//     SHOW_IN_RESULTLIST: true,
//     MANDATORY: false,
//     MULTIVALUED: false,
//     EXCLU_LAD: false,
//     FIXED_VALUES_TABLE: false,
//     IS_EXTERNAL: true,
//     VALEURS: {
//       1: "CONGES PAYES",
//       2: "RTT",
//       3: "AUTRES",
//       4: "CONGES SANS SOLDE",
//     },
//     ORDER: true,
//     ORDER_WAY: "asc",
//     TABLENAME: "FT_11_1",
//     FOREIGN_TABLE_ID: "55",
//     IS_PREDEFINED_LIST: false,
//     IS_DATE: false,
//     IS_INT: true,
//     IS_FLOAT: false,
//     IS_NUMERIC: true,
//     WIZARD: "",
//     SORTABLE: true,
//     STANDARDIZED_WIZARD: "",
//     Color_Id: "0",
//     Color_Code: "",
//   },
//   {
//     INDEX_ID: "153",
//     COLUMN: "custom_t4",
//     TYPE: "TEXT",
//     LABEL: "Cong&eacute;s | Autres",
//     SHORT_LABEL: " Autres",
//     COLL_ID: "coll_11",
//     AUTOCOMPLETE: false,
//     SHOW_IN_RESULTLIST: true,
//     MANDATORY: false,
//     MULTIVALUED: false,
//     EXCLU_LAD: false,
//     FIXED_VALUES_TABLE: false,
//     IS_EXTERNAL: false,
//     IS_PREDEFINED_LIST: false,
//     IS_DATE: false,
//     IS_INT: false,
//     IS_FLOAT: false,
//     IS_NUMERIC: false,
//     WIZARD: "",
//     SORTABLE: true,
//     STANDARDIZED_WIZARD: "",
//     Color_Id: "0",
//     Color_Code: "",
//   },
//   {
//     INDEX_ID: "163",
//     COLUMN: "custom_t3",
//     TYPE: "USERS_LIST",
//     LABEL: "Validation | Valideur",
//     SHORT_LABEL: " Valideur",
//     COLL_ID: "coll_11",
//     AUTOCOMPLETE: false,
//     SHOW_IN_RESULTLIST: true,
//     MANDATORY: false,
//     MULTIVALUED: false,
//     EXCLU_LAD: false,
//     FIXED_VALUES_TABLE: false,
//     IS_EXTERNAL: true,
//     VALEURS: {
//       "70590a02a99e1c061eac0318af82a7ae": "Admin 269 ",
//       "28e3edb2369c1c89447a760f920914cc": "devspe ",
//     },
//     ORDER: false,
//     TABLENAME: "users",
//     FOREIGN_TABLE_ID: "62",
//     IS_PREDEFINED_LIST: false,
//     IS_DATE: false,
//     IS_INT: false,
//     IS_FLOAT: false,
//     IS_NUMERIC: false,
//     WIZARD: "",
//     SORTABLE: true,
//     STANDARDIZED_WIZARD: "",
//     Color_Id: "0",
//     Color_Code: "",
//   },
//   {
//     INDEX_ID: "165",
//     COLUMN: "custom_n1",
//     TYPE: "FOREIGN_TABLE",
//     LABEL: "Validation | Statut de validation",
//     SHORT_LABEL: " Statut de validation",
//     COLL_ID: "coll_11",
//     AUTOCOMPLETE: false,
//     SHOW_IN_RESULTLIST: true,
//     MANDATORY: false,
//     MULTIVALUED: false,
//     EXCLU_LAD: true,
//     FIXED_VALUES_TABLE: false,
//     IS_EXTERNAL: true,
//     VALEURS: {
//       1: "A valider",
//       2: "Validé N1",
//       3: "Validé partiellement N1",
//       4: "Validé",
//       5: "Refusé",
//     },
//     ORDER: true,
//     ORDER_WAY: "asc",
//     TABLENAME: "def_values_11",
//     FOREIGN_TABLE_ID: "63",
//     IS_PREDEFINED_LIST: false,
//     IS_DATE: false,
//     IS_INT: true,
//     IS_FLOAT: false,
//     IS_NUMERIC: true,
//     WIZARD: "",
//     SORTABLE: true,
//     STANDARDIZED_WIZARD: "",
//     Color_Id: "0",
//     Color_Code: "",
//   },
//   {
//     INDEX_ID: "191",
//     COLUMN: "custom_d1",
//     TYPE: "DATE",
//     LABEL: "Validation | Date de d&eacute;but",
//     SHORT_LABEL: " Date de d&eacute;but",
//     COLL_ID: "coll_11",
//     AUTOCOMPLETE: false,
//     SHOW_IN_RESULTLIST: true,
//     MANDATORY: false,
//     MULTIVALUED: false,
//     EXCLU_LAD: false,
//     FIXED_VALUES_TABLE: false,
//     IS_EXTERNAL: false,
//     IS_PREDEFINED_LIST: false,
//     IS_DATE: true,
//     IS_INT: false,
//     IS_FLOAT: false,
//     IS_NUMERIC: false,
//     WIZARD: "",
//     SORTABLE: true,
//     STANDARDIZED_WIZARD: "",
//     Color_Id: "0",
//     Color_Code: "",
//   },
//   {
//     INDEX_ID: "192",
//     COLUMN: "custom_d2",
//     TYPE: "DATE",
//     LABEL: "Validation | Date de fin",
//     SHORT_LABEL: " Date de fin",
//     COLL_ID: "coll_11",
//     AUTOCOMPLETE: false,
//     SHOW_IN_RESULTLIST: true,
//     MANDATORY: false,
//     MULTIVALUED: false,
//     EXCLU_LAD: false,
//     FIXED_VALUES_TABLE: false,
//     IS_EXTERNAL: false,
//     IS_PREDEFINED_LIST: false,
//     IS_DATE: true,
//     IS_INT: false,
//     IS_FLOAT: false,
//     IS_NUMERIC: false,
//     WIZARD: "",
//     SORTABLE: true,
//     STANDARDIZED_WIZARD: "",
//     Color_Id: "0",
//     Color_Code: "",
//   },
//   {
//     INDEX_ID: "222",
//     COLUMN: "custom_t2",
//     TYPE: "TEXT",
//     LABEL: "Traitement |Trait&eacute;e le",
//     SHORT_LABEL: "Trait&eacute;e le",
//     COLL_ID: "coll_11",
//     AUTOCOMPLETE: false,
//     SHOW_IN_RESULTLIST: true,
//     MANDATORY: false,
//     MULTIVALUED: false,
//     EXCLU_LAD: true,
//     FIXED_VALUES_TABLE: false,
//     IS_EXTERNAL: false,
//     IS_PREDEFINED_LIST: false,
//     IS_DATE: false,
//     IS_INT: false,
//     IS_FLOAT: false,
//     IS_NUMERIC: false,
//     WIZARD: "",
//     SORTABLE: true,
//     STANDARDIZED_WIZARD: "",
//     Color_Id: "0",
//     Color_Code: "",
//   },
// ];

function App() {
  let user = window.user;
  let documentData = window.documentData;
  let tableauIndex = window.tableauIndex;

  return (
    <div className="App">
      <Form
        user={user}
        documentData={documentData}
        tableauIndex={tableauIndex}
      />
    </div>
  );
}

export default App;
